#!/bin/bash

rm -d Table_*.txt
./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_nominal --mzero 500 --mhalf 560 > Table_500_560_nominal.txt
./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_nominal --mzero 1000 --mhalf 400 > Table_1000_400_nominal.txt
./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_nominal --mzero 2500 --mhalf 240 > Table_2500_240_nominal.txt

./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_NoSigNonBkg20Sig20 --mzero 500 --mhalf 560 > Table_500_560_NoSigNonBkg20Sig20.txt
./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_NoSigNonBkg20Sig20 --mzero 1000 --mhalf 400 > Table_1000_400_NoSigNonBkg20Sig20.txt
./demo -d 2012-03-01-18-10-DemoPoint_cMSSM_NoSigNonBkg20Sig20 --mzero 2500 --mhalf 240 > Table_2500_240_NoSigNonBkg20Sig20.txt
