#!/bin/bash

function get () {
	RESULT=`grep -m $5 $1 $4 | cut -b $2-$3`
	if [ "$RESULT" = '' ]
	then
	   RESULT=0.0
	fi
	return
}  

OPTIONS=1
#OUTPUT="scan.dat"
#rm -f $OUTPUT
#FILE=isajet_200_200_50_0_1_170.9.dat
FILE=$1
OUTPUT=$2
touch $OUTPUT

#MSuGra parameters
MZERO=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b -10`
MHALF=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b 11-20`
AZERO=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b 21-30`
TANB=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b 31-40`
SGNMU=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b 41-48`
MTOP=`grep -m 1 -A 1 "M_0,  M_(1/2)" $FILE | grep -v "M_0,  M_(1/2)" | cut -b 49-58`

#Model parameters
get "1/alpha_em" 14 26 $FILE $OPTIONS
iALPHAEM=$RESULT

get "M_1" 14 26 $FILE $OPTIONS
M1=$RESULT

get "mu(Q)" 14 26 $FILE $OPTIONS
muQ=$RESULT

get "M_H1" 14 26 $FILE $OPTIONS
MH1sq=$RESULT

get "2(thetaw)" 43 53 $FILE $OPTIONS
THETA_W=$RESULT

get "M_2" 43 53 $FILE $OPTIONS
M2=$RESULT

get "B(Q)" 43 53 $FILE $OPTIONS
BQ=$RESULT

get "M_H2" 43 53 $FILE $OPTIONS
MH2sq=$RESULT

get "a_s" 65 90 $FILE $OPTIONS
ALPHAS=$RESULT

get "M_3" 65 90 $FILE $OPTIONS
M3=$RESULT

get "mu(Q)" 65 90 $FILE $OPTIONS
Q=$RESULT

get "TANBQ" 65 90 $FILE $OPTIONS
TANBQ=$RESULT


#SUSY masses
get "M(GL)" 10 18 $FILE $OPTIONS
MGL=$RESULT

get "M(UL)" 10 18 $FILE $OPTIONS
MUL=$RESULT

get "M(B1)" 10 18 $FILE $OPTIONS
MB1=$RESULT

get "M(SN)" 10 18 $FILE $OPTIONS
MSN=$RESULT

get "M(NTAU)" 10 18 $FILE $OPTIONS
MNTAU=$RESULT

get "M(Z1)" 10 18 $FILE $OPTIONS
MZ1=$RESULT

get "M(W1)" 10 18 $FILE $OPTIONS
MW1=$RESULT

get "M(HL)" 10 18 $FILE $OPTIONS
MHL=$RESULT

get "M(UR)" 30 38 $FILE $OPTIONS
MUR=$RESULT

#get "M(UR)" 30 38 $FILE $OPTIONS
#MUR=$RESULT

get "M(B2)" 30 38 $FILE $OPTIONS
MB2=$RESULT

get "M(EL)" 30 38 $FILE $OPTIONS
MEL=$RESULT

get "M(TAU1)" 30 38 $FILE $OPTIONS
MTAU1=$RESULT

get "M(Z2)" 30 38 $FILE $OPTIONS
MZ2=$RESULT

get "M(W2)" 30 38 $FILE $OPTIONS
MW2=$RESULT

get "M(HH)" 30 38 $FILE $OPTIONS
MHH=$RESULT

get "M(DL)" 50 58 $FILE $OPTIONS
MDL=$RESULT

get "M(T1)" 50 58 $FILE $OPTIONS
MT1=$RESULT

get "M(ER)" 50 58 $FILE $OPTIONS
MER=$RESULT

get "M(TAU2)" 50 58 $FILE $OPTIONS
MTAU2=$RESULT

get "M(Z3)" 50 58 $FILE $OPTIONS
MZ3=$RESULT

get "M(HA)" 50 58 $FILE $OPTIONS
MHA=$RESULT

get "M(DR)" 70 78 $FILE $OPTIONS
MDR=$RESULT

get "M(T2)" 70 78 $FILE $OPTIONS
MT2=$RESULT

get "M(Z4)" 70 78 $FILE $OPTIONS
MZ4=$RESULT

get "M(H+)" 70 78 $FILE $OPTIONS
MHp=$RESULT

if [ "$SGNMU" != '' ]
then
	echo "$MZERO $MHALF $TANB $SGNMU $AZERO $MTOP $muQ $Q $M1 $M2 $M3 $MGL $MUL $MB1 $MSN $MNTAU $MZ1 $MW1 $MHL $MUR $MB2 $MEL $MTAU1 $MZ2 $MW2 $MHH $MDL $MT1 $MER $MTAU2 $MZ3 $MHA $MDR $MT2 $MZ4 $MHp" >> $OUTPUT
else
        echo "no solution for m0=$MZERO and m1/2=$MHALF"
fi
