#!/bin/bash

DONE=0
RUN=0
ABORT=0
SCHED=0
TOT=0
I=0
UNK=0

touch resubmit
NJOBS=`ls -d crab_* | wc -l`
JOBS=`ls -d crab_*`
for JOB in $JOBS
do
  #echo $JOB
  rm -f crap.tmp
  crab -status -continue $JOB > crap.tmp
  _DONE=`grep "   Done (Success)" crap.tmp | wc -l`
  _RUN=`grep "     Running   " crap.tmp | wc -l`
  _ABORT=`grep "     Aborted   " crap.tmp | wc -l`
  _SCHED=`grep "    Scheduled   " crap.tmp | wc -l`
  _TOT=`grep "Total Jobs" crap.tmp | cut -b 10-12`
  #_UNK=$(($_TOT-$_DONE-$_RUN-$_ABORT-$_SCHED))
  ABORTEDJOBS=`grep -A 1 "Jobs aborted" crap.tmp | grep "List of jobs" | cut -b 24-`
  if [ "$ABORTEDJOBS" != '' ]
  then
    echo "crab -resubmit $ABORTEDJOBS -continue $JOB" >> resubmit
  fi  
  #
  DONE=$(($DONE+$_DONE))
  RUN=$(($RUN+$_RUN))
  ABORT=$(($ABORT+$_ABORT))
  SCHED=$(($SCHED+$_SCHED))
  #TOT=$(($TOT+$_TOT))
  #UNK=$(($TOT-$DONE-$RUN-$ABORT-$SCHED))
  I=$(($I+1))
  #
  echo "Checked $I (of $NJOBS) directories:"
  echo "   current dir: $JOB"
  echo "-> $_DONE  ($DONE)  Done (Success)"
  echo "-> $_RUN  ($RUN)  Running"
  echo "-> $_ABORT  ($ABORT)  Aborted"
  echo "-> $_SCHED  ($SCHED)  Scheduled"
  #echo "-> $_UNK  ($UNK)  Unknown status"
  echo "-> $_TOT  ($TOT)  Total jobs"
  echo
done
