#!/bin/bash
#CTA, HH, 11/26/007

echo '...preparing jobs'
TIME=`date +%s`
SEED1=$(($TIME-1196000000))
SEED2=$(($TIME-1196001000))
SEED3=$(($TIME-1196002000))
SEED4=$(($TIME-1196003000))
SEED5=$(($TIME-1196004000))
SEED6=$(($TIME-1196005000))
SEED7=$(($TIME-1196006000))
SEED8=$(($TIME-1196007000))
SEED9=$(($TIME-1196008000))
SEED10=$(($TIME-1196009000))

#CRAB random seeds
./mkseeds.sh crab.orig > /dev/null

if [[ $# != 3 ]]; then
  echo 'Error - argument missing! '
  echo 'Expecting 3 arguments: <#total events> <mzero> <mhalf>. Try again!'
else
  #MZero
  sed -e 's/RMSS(8)=150./RMSS(8)='$2'./'                        Pythia_mSUGRA_incl.cfg > Pythia_mSUGRA_incl_$2.cfg.1.dummy
  #MHalf
  sed -e 's/RMSS(1)=100./RMSS(1)='$3'./'                        Pythia_mSUGRA_incl_$2.cfg.1.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.3.dummy
  #Random seeds
  sed -e 's/VtxSmeared   = 7654321/VtxSmeared = '$SEED1'/'     Pythia_mSUGRA_incl_$2_$3.cfg.3.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.4.dummy
  sed -e 's/g4SimHits    = 1122334/g4SimHits = '$SEED2'/'      Pythia_mSUGRA_incl_$2_$3.cfg.4.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.5.dummy
  sed -e 's/mix	     = 2233445/mix = '$SEED3'/'                Pythia_mSUGRA_incl_$2_$3.cfg.5.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.6.dummy
  sed -e 's/siPixelDigis = 3344556/siPixelDigis = '$SEED4'/'   Pythia_mSUGRA_incl_$2_$3.cfg.6.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.7.dummy
  sed -e 's/siStripDigis = 4455667/siStripDigis = '$SEED5'/'   Pythia_mSUGRA_incl_$2_$3.cfg.7.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.8.dummy
  sed -e 's/ecalUnsuppressedDigis = 5566778/ecalUnsuppressedDigis = '$SEED6'/'  Pythia_mSUGRA_incl_$2_$3.cfg.8.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.9.dummy
  sed -e 's/hcalDigis    = 6677889/hcalDigis = '$SEED7'/'      Pythia_mSUGRA_incl_$2_$3.cfg.9.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.10.dummy
  sed -e 's/muonCSCDigis = 7788990/muonCSCDigis = '$SEED8'/'   Pythia_mSUGRA_incl_$2_$3.cfg.10.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.11.dummy
  sed -e 's/muonDTDigis  = 8899001/muonDTDigis = '$SEED9'/'    Pythia_mSUGRA_incl_$2_$3.cfg.11.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.12.dummy
  sed -e 's/muonRPCDigis = 9900112/muonRPCDigis = '$SEED10'/'  Pythia_mSUGRA_incl_$2_$3.cfg.12.dummy > Pythia_mSUGRA_incl_$2_$3.cfg.13.dummy
  #Output
  rm -f Pythia_mSUGRA_incl_$2_$3.cfg
  sed -e 's/Pythia_mSUGRA_incl.root/Pythia_mSUGRA_incl_'$SEED2'_'$2'_'$3'.root/'  Pythia_mSUGRA_incl_$2_$3.cfg.13.dummy > Pythia_mSUGRA_incl_$2_$3.cfg
  #
  #CRAB stuff
  sed -e 's/pset=Pythia_mSUGRA_incl.cfg/pset=Pythia_mSUGRA_incl_'$2'_'$3'.cfg/' crab.orig > crab.1.dummy
  sed -e 's/output_file = Pythia_mSUGRA_incl.root/output_file = Pythia_mSUGRA_incl_'$SEED2'_'$2'_'$3'.root/' crab.1.dummy > crab.2.dummy
  sed -e 's/total_number_of_events=250/total_number_of_events='$1'/' crab.2.dummy > crab.cfg
  #rm dummy files  
  rm -f *.dummy
fi

echo 'Success! Created config file "Pythia_mSUGRA_incl_'$2'_'$3'.cfg" and linked crab.cfg accordingly.'
echo '-> Random number seeds are set.'
echo '-> m_zero = '$2
echo '-> m_half = '$3
echo '-> total number of events = '$1
echo 'To start submission, execute:'
echo '  crab -create -submit'
