#!/bin/bash
#k5log -principal auterman -c desy.de
cp $1/job*/*.result.txt $1/.
DIR=`basename $1`
ls $1/*.result.txt > $1/filelist.txt
tar -cf $DIR.tar $1/*.txt
gzip $DIR.tar
#rm -f $1/*.txt
cp $DIR.tar.gz  /afs/desy.de/user/a/auterman/temp/.
echo ""
echo "cp  /afs/desy.de/user/a/auterman/temp/$DIR.tar.gz . ; tar -xvzf $DIR.tar.gz"
